# Generated by Django 4.1.2 on 2022-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
    ]
