# Generated by Django 4.1.2 on 2022-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloner', '0002_jsondump'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdump',
            name='name',
            field=models.CharField(default='RepoName', max_length=20),
            preserve_default=False,
        ),
    ]
