# Generated by Django 4.1.2 on 2022-11-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloner', '0004_jsondump_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondump',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Linkdump', to='cloner.linkdump'),
            preserve_default=False,
        ),
    ]
