# Generated by Django 4.1.2 on 2022-11-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloner', '0005_jsondump_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondump',
            name='id',
        ),
        migrations.AlterField(
            model_name='jsondump',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Linkdump', serialize=False, to='cloner.linkdump'),
        ),
    ]
